set_property -dict [list \
	CONFIG_VOLTAGE {3.3} \
	CFGBVS {VCCO} \
	BITSTREAM.CONFIG.SPI_BUSWIDTH {4} \
	BITSTREAM.CONFIG.SPI_32BIT_ADDR {YES} \
	BITSTREAM.CONFIG.CONFIGRATE {66} \
	BITSTREAM.CONFIG.M0PIN {PULLNONE} \
	BITSTREAM.CONFIG.M1PIN {PULLNONE} \
	BITSTREAM.CONFIG.M2PIN {PULLNONE} \
	BITSTREAM.CONFIG.UNUSEDPIN {PULLDOWN} \
	BITSTREAM.GENERAL.COMPRESS {TRUE} \
	] [current_design]
